version: '3'
services:
  web:
    build: .
    volumes:
      - ./src/static/:/app/static
      - ./src/media/:/app/media
    container_name: web
    depends_on:
      - mysql
    environment:
      DB_URL: mysql://root:${MYSQL_ROOT_PASSWORD}@mysql:3306/fast_store_backend # 类似：mysql://root:123@mysql:3306/fast_store_backend
      DOMAIN_NAME: ${DOMAIN_NAME} # 服务器地址
      WECHAT_APPID: ${WECHAT_APPID}
      WECHAT_SECRET: ${WECHAT_SECRET}
  mysql:
    image: mysql:8.0
    volumes:
      - ./mysql/db:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    restart: always
    ports:
      - 8750:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} #访问密码
  nginx:
    image: nginx:1.21.6-alpine
    restart: always
    container_name: nginx
    depends_on:
      - web
    environment:
      TZ: Asia/Shanghai
    ports:
      - "443:443"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/ # nginx的代理配置
      - ./nginx/logs:/var/log/nginx/
      - ./nginx/ssl:/etc/nginx/ssl/ # ssl需要的crt和key
      - ./src/static/:/app/static/
      - ./src/media/:/app/media/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
