version: '3'
services:
  web:
    build: .
    volumes:
      - ./static/:/app/static
      - ./media/:/app/media
    container_name: web
    environment:
      DB_URL: mysql://root:${MYSQL_ROOT_PASSWORD}@mysql:3306/fast_store_backend # 类似：mysql://root:123@mysql:3306/fast_store_backend
      PATH: ${PATH} # 服务器地址，
  mysql:
    image: mysql:8.0
    volumes:
      - ./mysql/db:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    restart: always
    ports:
      - 8750:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} #访问密码
  nginx:
    image: nginx:1.21.6-alpine
    restart: always
    container_name: nginx
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "443:443"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
      - ./site:/usr/share/nginx/html
      - ./nginx/letsencrypt:/etc/letsencrypt
      - ./nginx/vjoy.vip_nginx:/etc/nginx/ssl
